In [262]:
import numpy as np
### Input file into lines
with open('input.txt') as f:
    input = f.read()

lines = input.strip().split('\n')
res = [[int(x) for x in str(i)] for i in lines]
a = np.array(res)

b = np.sum(a, axis = 0)
gamma_array = np.floor(b/(len(lines)/2))
gamma_array = [int(i) for i in gamma_array]
epsilon_array = [(i+1)%2 for i in gamma_array]

gamma_array_str = [str(i) for i in gamma_array]
epsilon_array_str = [str(i) for i in epsilon_array]
gamma = ''.join(gamma_array_str)
epsilon = ''.join(epsilon_array_str)

print(int(gamma,2)*int(epsilon,2))

In [264]:
a = np.array(res)

In [265]:
b = np.sum(a, axis = 0)

In [266]:
gamma_array = np.floor(b/(len(lines)/2))

In [267]:
gamma_array = [int(i) for i in gamma_array]
epsilon_array = [(i+1)%2 for i in gamma_array]
gamma_array_str = [str(i) for i in gamma_array]
epsilon_array_str = [str(i) for i in epsilon_array]

In [268]:
gamma = ''.join(gamma_array_str)
epsilon = ''.join(epsilon_array_str)

In [269]:
int(gamma,2)*int(epsilon,2)

4006064

### Part 2

In [270]:
place = 0
c = a
while len(c) > 1:
    f = np.sum(c, axis = 0)
    gamma_array = (np.floor(f/((len(c))/2)))
    gamma_array = [int(i) for i in gamma_array]
    gamma_array = [1 if i == 2 else i for i in gamma_array]
    if(len(c) > 1):
        c = [i for i in c if i[place] == gamma_array[place]]
    place += 1

[484 501 519 496 493 504 485 504 487 499 490 494]
1000
[0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0]
[  0 263 261 261 255 266 255 264 250 255 241 254]
516
[0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0]
[  0 263 137 128 130 132 131 137 121 129 126 126]
263
[0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0]
[  0 137 137  67  65  67  71  71  58  72  61  61]
137
[0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[ 0 70 70  0 33 36 41 37 24 35 33 27]
70
[0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[ 0 37 37  0  0 18 21 19 10 22 20 15]
37
[0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0]
[ 0 19 19  0  0  0 11 12  6 10 12  9]
19
[0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0]
[ 0 11 11  0  0  0 11  6  4  4  6  5]
11
[0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0]
[0 6 6 0 0 0 6 6 3 3 5 3]
6
[0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1]
[0 3 3 0 0 0 3 3 3 2 2 2]
3
[0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1]
[0 2 2 0 0 0 2 2 2 2 2 1]
2
[0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1]
[0 2 2 0 0 0 2 2 2 2 2 1]
2
[0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1]


In [271]:
place = 0
d = a
while len(d) > 1:
    f = np.sum(d, axis = 0)
    gamma_array = (np.floor(f/((len(d))/2)))
    gamma_array = [int(i) for i in gamma_array]
    epsilon_array = [(i+1)%2 for i in gamma_array]
    d = [i for i in d if i[place] == epsilon_array[place]]
    place += 1

In [272]:
d

[array([1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0])]

In [273]:
c

[array([0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1])]

In [274]:
c = [int(i) for i in c[0]]
d = [int(i) for i in d[0]]
ox_str = [str(i) for i in c]
co2_str = [str(i) for i in d]
ox = ''.join(ox_str)
co2 = ''.join(co2_str)
print(ox,co2,int(ox,2)*int(co2,2))

011000111111 111010000100


In [275]:
print(ox,co2,int(ox,2)*int(co2,2))

011000111111 111010000100 5941884
